version: '2'
services:
  zookeeper:
    build: .
    ports:
      - "2181:2181"
    command: zookeeper

  kafka:
    build: .
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER=zookeeper
    command: kafka
