#!/usr/bin/env bash

KAFKA_OPTIONS=""

if [[ -z $KAFKA_ZOOKEEPER ]]; then
    KAFKA_ZOOKEEPER=localhost
fi

if [[ -z $KAFKA_ADVERTISED_HOST_NAME ]]; then
    KAFKA_ADVERTISED_HOST_NAME=localhost
fi

$KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server.properties --override zookeeper.connect=$KAFKA_ZOOKEEPER:2181 --override advertised.host.name=$KAFKA_ADVERTISED_HOST_NAME
